server:
  port: 8306
spring:
  application:
    name: consul-ribbon-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #这只Sleuth的抽样收集概率
  cloud:
    consul: #Consul服务注册发现配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
service-url:
  user-service: http://consul-user-service

