server:
  port: 8306
spring:
  application:
    name: consul-ribbon-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #这只Sleuth的抽样收集概率
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
service-url:
  user-service: http://nacos-user-service

