server:
  port: 9401
spring:
  application:
    name: oauth2-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/